# see https://minimo.netlify.com/docs/installation/

baseurl = "https://darongmean.com"
title = "Darong Mean"
copyright = ""
theme = "minimo"
googleAnalytics = "UA-75628175-2"
disqusShortname = ""
Paginate = 5
preserveTaxonomyNames = true
enableRobotsTXT = true
pygmentsCodefences = true
defaultContentLanguage = "en"

[params.info]
description = "Programmer - (Procrastinating) Blogger - (Casual) Gamer"
title404 = "Nothing's here!"

[params.assets]
favicon = "images/favicon.ico"
customCSS = []
customJS = []
gopher = ""

[params.copyright]
prefix = ""
holder = "Darong Mean"
startYear = "2016"
suffix = ""

[params.settings]
dateFormat = "2006, Jan 02"
listDateFormat = "2006, Jan 02"
hideEntryNavigation = ["page"]
recentPostsLength = 100
hideSocialMenu = false
showReadingTime = true
noTermCloudShuffle = false
homepageSections = ["recent_posts"]

[params.opengraph.facebook]
admins = []
appID = ""
pageID = ""

[params.opengraph.twitter]
page = ""

[params.seo]
titleSeparator = "â€¢"

[params.social]
github = "darongmean"
linkedin = "darongm"
twitter = "darong_mean"

[params.social.config]
platforms = ["github","facebook","twitter","instagram","email","codepen","linkedin","telegram","google_scholar"]

[taxonomies]
author = "authors"
category = "categories"
tag = "tags"

[permalinks]
page = "/:slug/"

[[menu.main]]
name = "Blog"
weight = -10
identifier = "post"
url = "/"

[blackfriday]
hrefTargetBlank = true

[languages]
[languages.en]
lang = "en"
languageName = "English"
weight = 1

[params]
# Enable rollbar.com
enableRollbar = true
rollbarAccessToken = "43aac4bbe89e471eb0c4e16dddc06414"
rollbarEnvironment = "production"

